# Generated by Django 4.2.3 on 2023-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('HomeTel', models.CharField(max_length=9)),
                ('MobileTel', models.CharField(max_length=9)),
                ('State', models.CharField(max_length=10)),
                ('BusinessId', models.CharField(max_length=5)),
                ('DepartmentId', models.CharField(max_length=5)),
                ('UnitId', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
