# Generated by Django 4.2.3 on 2023-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Id',
            new_name='EmpId',
        ),
    ]
